### ISSUE TITLE
Load Balancing - Round Robin

### ISSUE THREAD

**Issue by parkinsona** [thinktecture/Thinktecture.IdentityServer.v3#692]
Hi,

We are putting identity server behind our load balancer and found it works well with sticky requests.
However, when we switch the load balancer to round robin we get the following:

```
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
   at Microsoft.Owin.Security.DataProtection.AppBuilderExtensions.CallDataProtectionProvider.CallDataProtection.Unprotect(Byte[] protectedData) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Configuration\IdentityServerServiceFactory.cs:line 0
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.MessageCookie`1.Unprotect(String data, IDataProtector protector) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Configuration\Hosting\MessageCookie.cs:line 74
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.MessageCookie`1.Read(String id) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Configuration\Hosting\MessageCookie.cs:line 154
   at Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController.<Login>d__0.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Endpoints\AuthenticationController.cs:line 74

```

Is identity server designed to work with this style of load balancing?

**Comment by parkinsona** [comment]
Thanks for your help. From my reading, it looks like SHA1 is the best of the options available in IIS. Even thought SHA1 appears to be on its way out.

**Comment by pessimca** [comment]
We are facing same issue with load balancer. Could you please help us to configure identity server on differnt nodes with load balancer.

**Comment by brockallen** [comment]
It's in the docs: https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html

**Comment by pessimca** [comment]
Thanks for you quick response. We tried with these options:
RequireSsl = false
PublicOrigin = << One of the Node address>>
We are getting this message: "An existing connction was forcibily closed by remove host"

I believe, you have seen this configuration many times in your side, Let me get you more details again from my end:
* We have two nodes (Node-1, Node-2 which internally connects with LB using port 80) with Load balancer (which has HTTPS)
* Configured Identity Server as website under both nodes
* Both nodes are using same database connection
* Set false to RequireSsl

* Tried - Set Node-1 address to PublicOrigin to test connectivity (by disabling Node-2 IIS) --- Same Error
* Also, tried with direct url which is accessible by user with points LB VIP -- Same Error
*BTW, this configuration working fine on dev environment which has only one node and no LB

Please let me know if we are missing anything

Also, I see your docs which is talking about Signing Keys.. Could you please share more details about this. Is this mandatory step to configure IDS on servers?

I appreciate all your help to fix my issues.

Thank you.

**Comment by leastprivilege** [comment]
You set the public origin to the "public name of the load balancer" - like

https://login.myapp.com

**Comment by pessimca** [comment]
Yes. First i tried with the same and getting  below error:
"An existing connection was forcibly closed by the remote host"

Do we need any other settings other than RequireSsl and PublicOrigin ?

**Comment by leastprivilege** [comment]
Only the settings described in documentation.

**Comment by pessimca** [comment]
Finally, we are able to access identity server with loadbalancer. Thank you.

**Comment by leastprivilege** [comment]
so do you care to explain how you fixed it?

**Comment by pessimca** [comment]
We used SSL flag to false and added publicorgin to LB VIP url.

We need enable SNOT if Identity Server and Clients are running on same nodes and lb. Otherwise it will not communicate with each other.
All these resolved our issues and applications are working good.

**Comment by idqfizz** [comment]
please explain SNOT. i'm facing simmilar problems with the same setup.
