### ISSUE TITLE
Exception when trying to get access token: "Invalid hashing algorithm for client secret."

### ISSUE THREAD

**Issue by KalvisUpitis** [thinktecture/Thinktecture.IdentityServer.v3#741]
I have setup IdentityServer using the latest package version from your Dev NuGet repo -  "1.0.0-pre-10043".

Now I'm trying to use it for my Rest services (similar use case as covered here: https://github.com/thinktecture/Thinktecture.IdentityServer.v3.Samples/tree/master/source/MVC%20Authentication/EmbeddedMvc).

At first I was struggling with the Client secret configuration which was different in the latest version as it is in a sample (client secret is a list of ClientSecret objects instead of single string), so I configured the client in the following way:

``` C#
return new Client
{
	Enabled = true,
	ClientName = "Sample API",
	ClientId = "SampleAPI",
	ClientSecrets = new List<ClientSecret>()
	{
		new ClientSecret("S@mpl3AP1")
	},
	Flow = Flows.ClientCredentials
}
```

Now when the access token request is executed (see code snippet below) service throws an exception: "Invalid hashing algorithm for client secret.". Full exception details you can find below.

``` C#
var client = new OAuth2Client(
                new Uri("http://login.sampleapp.local/connect/token"),
                "SampleAPI",
                "S@mpl3AP1");

            return await client.RequestClientCredentialsAsync("IdentityManager");
```
Exception:
```
System.InvalidOperationException: Invalid hashing algorithm for client secret.
   at Thinktecture.IdentityServer.Core.Services.Default.HashedClientSecretValidator.ValidateClientSecretAsync(Client client, String secret) in c:\projects\thinktecture-identityserver-v3\source\Core\Services\Default\HashedClientSecretValidator.cs:line 80
   at Thinktecture.IdentityServer.Core.Validation.ClientValidator.<ValidateClientCredentialsAsync>d__5.MoveNext() in c:\projects\thinktecture-identityserver-v3\source\Core\Validation\ClientValidator.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Validation.ClientValidator.<ValidateClientAsync>d__0.MoveNext() in c:\projects\thinktecture-identityserver-v3\source\Core\Validation\ClientValidator.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<ProcessAsync>d__5.MoveNext() in c:\projects\thinktecture-identityserver-v3\source\Core\Endpoints\Connect\TokenEndpointController.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<Post>d__0.MoveNext() in c:\projects\thinktecture-identityserver-v3\source\Core\Endpoints\Connect\TokenEndpointController.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http908531.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Core\Tokens\GenericUserNameSecurityTokenHandler.cs:line 0
```

**Comment by KalvisUpitis** [comment]
Same example works when dwngraded IdentityServer to the beta package versions from Nuget oficial repository and changed Client config to a single-string Client Secret.

**Comment by leastprivilege** [comment]
We demand hashed client secrets from now on -simply change your code to:

return new Client
{
    Enabled = true,
    ClientName = "Sample API",
    ClientId = "SampleAPI",
    ClientSecrets = new List<ClientSecret>()
    {
        new ClientSecret("S@mpl3AP1".Sha256())
    },
    Flow = Flows.ClientCredentials
}

**Comment by gjlumsden** [comment]
@leastprivilege This is a great improvement, and answers a query I had before the RC hit NuGet. However, what is now the best approach for those with registered Clients in my system to view and retrieve their client secrets given this is now a one-way hash? Will I need to provide the ability to create a new secret should their old one be forgotten or lost, and display only once after it has been generated? After this time it can only be used and never viewed again?

**Comment by brockallen** [comment]
Yes, once you give it to the client you won't be able to get it again. If needed, just create a new one. Also, there's an optional expiration on the `ClientSecret` so you know when you can delete them from IdSvr.

**Comment by gjlumsden** [comment]
@brockallen Great, that makes perfect sense. Thanks.
