### ISSUE TITLE
Resolve failed in RequireSSL middleware

### ISSUE THREAD

**Issue by johnkors** [thinktecture/Thinktecture.IdentityServer.v3#747]
Hi,

After update to beta4-1 we see alot of ERROR log statements.

```
 at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Validation\TokenValidator.cs:line 0
   at Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.ResolveDependency[T](IDictionary`2 env) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Extensions\OwinExtensions.cs:line 90
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.RequireSslMiddleware.<Invoke>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\Hosting\RequireSslMiddleware.cs:line 39

```

Seems it's not able to resolve the ILocalizationService, but we have not yet begun to look at localization. I guess it should be able to resolve a default implementation of that service?

**Comment by leastprivilege** [comment]
that's a bug - fixed on dev. Or on RC later today.

**Comment by johnkors** [comment]
Thanks :)
