### ISSUE TITLE
Error occurred during a cryptographic operation

### ISSUE THREAD

**Issue by fatagun** [thinktecture/Thinktecture.IdentityServer.v3#771]
Hello I am getting the following error. not sure what s the cause? 

`System.Security.Cryptography.CryptographicException was unhandled by user code
  HResult=-2146233296
  Message=Error occurred during a cryptographic operation.
  Source=System.Web
  StackTrace:
       at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
       at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.Unprotect(Byte[] protectedData)
       at System.Web.Security.MachineKey.Unprotect(ICryptoServiceProvider cryptoServiceProvider, Byte[] protectedData, String[] purposes)
       at System.Web.Security.MachineKey.Unprotect(Byte[] protectedData, String[] purposes)
       at Microsoft.Owin.Host.SystemWeb.DataProtection.MachineKeyDataProtector.Unprotect(Byte[] protectedData)
       at Microsoft.Owin.Security.DataProtection.AppBuilderExtensions.CallDataProtectionProvider.CallDataProtection.Unprotect(Byte[] protectedData) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
       at Thinktecture.IdentityServer.Core.Configuration.Hosting.HostDataProtector.Unprotect(Byte[] data, String entropy) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Configuration\Hosting\HostDataProtector.cs:line 39
       at Thinktecture.IdentityServer.Core.Configuration.Hosting.DataProtectorAdapter.Unprotect(Byte[] protectedData) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Configuration\Hosting\DataProtectorAdapter.cs:line 37
       at Microsoft.Owin.Security.DataHandler.SecureDataFormat`1.Unprotect(String protectedText) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
  InnerException: `

**Comment by brockallen** [comment]
I think you'll need to provide more context.

**Comment by fatagun** [comment]
I was getting this on a workstation, on a different one, i m not getting. If i encounter again, i ll post it.

Thanks.
