### ISSUE TITLE
How to remove IdSrv cookies

### ISSUE THREAD

**Issue by DmitryNaumov** [thinktecture/Thinktecture.IdentityServer.v3#789]
I have case when browser's cookies issued by idsrv are no longer valid. I know how we ran into this situation (new VM with old address) and it's ok. One thing I need is the way to clear cookies when exception happens:

2015-01-20 18:10:18,390 [4296:68] ERROR ErrorPageFilterAttribute - Exception accessing: /core/login
System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at System.Security.Cryptography.DpapiDataProtector.ProviderUnprotect(Byte[] encryptedData)
   at System.Security.Cryptography.DataProtector.Unprotect(Byte[] encryptedData)
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.AntiForgeryTokenValidator.GetCookieToken(IDictionary`2 env)
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.AntiForgeryTokenValidator.GetAntiForgeryHiddenInput(IDictionary`2 env)
   at Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController.<RenderLoginPage>d__61.MoveNext()

I do the same with SAM/FAM and looking for way to do this in IdSrv, please advice.

**Comment by brockallen** [comment]
Are you on the RC? Someone submitted a PR to cleanup old cookies protected with a different data protector. Maybe we missed one?

**Comment by DmitryNaumov** [comment]
I have this issue using beta3-3. Should upgrading to RC help?

**Comment by DmitryNaumov** [comment]
I glanced at PR and looks like it may solve my problem, I'll give it a try.
